const {installAccessProbe,assertAccess}=require('./access-probe.cjs');
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{for(const mobile of [true,false]){
 const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1280,height:1000},isMobile:mobile,hasTouch:mobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const requests=[];await page.route(/^https?:/,r=>{requests.push(r.request().url());return r.abort();});await installAccessProbe(page);await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 const press=async s=>page.locator(s)[mobile?'tap':'click']();const toggle=async()=>{for(let i=0;i<5;i++)await press('#game-title');};
 const state=()=>page.evaluate(()=>JSON.stringify({puzzleIndex,placed,history,selected,shape,selectedPlaced,message:$('message').textContent,error:$('message').classList.contains('error')}));
 async function placeStep(index){const data=await page.evaluate(index=>{const a=SOLUTIONS[puzzle().number][index];selectPiece(a.id);return a;},index);
 // Reach target orientation through real rotate/flip controls.
 let found=false;for(let f=0;f<2&&!found;f++){for(let r=0;r<6;r++){found=await page.evaluate(a=>E.key(shape)===E.key(a.cells),data);if(found)break;await press('#right');}if(!found)await press('#flip');}assert.ok(found);
 const c=await page.evaluate(a=>{const n=E.normalize(a.cells),dx=a.cells[0][0]-n[0][0],dy=a.cells[0][1]-n[0][1];return [shape[0][0]+dx,shape[0][1]+dy,shape[0][2]];},data);
 const loc=page.locator(`.cell[data-x="${c[0]}"][data-y="${c[1]}"][data-t="${c[2]}"]`);assert.ok((await loc.getAttribute('class')).includes('legal'));
 // Tap triangle centroid: bounding-box center may lie on a neighboring triangle.
 await loc.scrollIntoViewIfNeeded();const pt=await loc.evaluate(el=>{const v=el.querySelector('polygon').points,m=el.getScreenCTM();return {x:(v[0].x+v[1].x+v[2].x)/3*m.a+m.e,y:(v[0].y+v[1].y+v[2].y)/3*m.d+m.f};});
 if(mobile)await page.touchscreen.tap(pt.x,pt.y);else await page.mouse.click(pt.x,pt.y);
 assert.equal(await page.evaluate(()=>placed.length),index+1,JSON.stringify({problem:await page.evaluate(()=>puzzle().number),index,message:await page.locator('#message').textContent()}));
 }
 assert.equal(await page.locator('#admin-tools').isVisible(),false);for(let i=0;i<4;i++)await press('#game-title');await page.waitForTimeout(2100);await press('#game-title');assert.equal(await page.locator('#admin-tools').isVisible(),false);await page.waitForTimeout(2100);await toggle();
 await placeStep(0);await page.locator('.piece').first()[mobile?'tap':'click']();await press('#left');const before=await state();await press('#show-answer');for(const id of ['problem','left','right','flip','remove','undo','restart'])assert.ok(await page.locator('#'+id).isDisabled());assert.equal(await page.locator('#clear').isVisible(),false);await page.evaluate(()=>activate(0,0,0));await press('#close-answer');assert.equal(await state(),before);await press('#show-answer');await toggle();assert.equal(await state(),before);await press('#undo');assert.equal(await page.evaluate(()=>placed.length),0);await toggle();
 for(let i=0;i<25;i++){await page.selectOption('#problem',String(i));const before=await state();await press('#show-answer');assert.equal(await page.locator('.cell.occupied').count(),await page.evaluate(()=>SOLUTIONS[puzzle().number].reduce((n,a)=>n+a.cells.length,0)));await press('#close-answer');assert.equal(await state(),before);
 const count=await page.evaluate(()=>puzzle().pieces.length);for(let j=0;j<count;j++)await placeStep(j);assert.ok(await page.locator('#clear').isVisible());assert.equal(await page.locator('#difficulty').textContent(),'★'.repeat(Math.floor(i/5)+1));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.screenshot({path:path.resolve(__dirname,`../analysis/${mobile?'mobile':'desktop'}.png`),fullPage:true});await press('#restart');assert.equal(await page.evaluate(()=>placed.length),0);await placeStep(0);await page.evaluate(()=>{selectedPlaced=placed[0].id;render();});await press('#remove');assert.equal(await page.evaluate(()=>placed.length),0);await press('#undo');assert.equal(await page.evaluate(()=>placed.length),1);await assertAccess(page,requests,1);await page.reload();await assertAccess(page,requests,2);assert.equal(await page.locator('#admin-tools').isVisible(),false);assert.deepEqual(errors,[]);await page.close();
 }console.log('PASS: desktop/mobile, all 25 clears, transformations, admin timeout/read-only/restoration/reload, undo/remove/restart, layout, one access GET per load, no extra requests during operations, game works with network failure.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
